// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortListOfHospitalManagement.Context;

#nullable disable

namespace ShortListOfHospitalManagement.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20240523083951_Initial4")]
    partial class Initial4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.Allergies_Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AllergyID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AllergyID");

                    b.HasIndex("PatientID");

                    b.ToTable("Allergies_Details");
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.Allergy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AllergyName = "Drugs-Penicillin"
                        },
                        new
                        {
                            ID = 2,
                            AllergyName = "Drugs-Others"
                        },
                        new
                        {
                            ID = 3,
                            AllergyName = "Animals"
                        },
                        new
                        {
                            ID = 4,
                            AllergyName = "Food"
                        },
                        new
                        {
                            ID = 5,
                            AllergyName = "Oinments"
                        },
                        new
                        {
                            ID = 6,
                            AllergyName = "Plants"
                        },
                        new
                        {
                            ID = 7,
                            AllergyName = "Sprays"
                        },
                        new
                        {
                            ID = 8,
                            AllergyName = "Other"
                        });
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.DiseaseInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DiseaseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DiseaseInformations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiseaseName = "Fever"
                        },
                        new
                        {
                            ID = 2,
                            DiseaseName = "Chickenpox"
                        },
                        new
                        {
                            ID = 3,
                            DiseaseName = "COVID-19"
                        },
                        new
                        {
                            ID = 4,
                            DiseaseName = "Measles"
                        },
                        new
                        {
                            ID = 5,
                            DiseaseName = "Meningitis"
                        },
                        new
                        {
                            ID = 6,
                            DiseaseName = "Monkeypox"
                        });
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.NCD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NCDName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NCDs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NCDName = "Asthma"
                        },
                        new
                        {
                            ID = 2,
                            NCDName = "Cancer"
                        },
                        new
                        {
                            ID = 3,
                            NCDName = "Disorder of ear"
                        },
                        new
                        {
                            ID = 4,
                            NCDName = "Disorder of eye"
                        },
                        new
                        {
                            ID = 5,
                            NCDName = "Mental Illness"
                        },
                        new
                        {
                            ID = 6,
                            NCDName = "Oral Health Problem"
                        },
                        new
                        {
                            ID = 7,
                            NCDName = "Hypertension"
                        });
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.NCD_Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("NCDID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NCDID");

                    b.HasIndex("PatientID");

                    b.ToTable("NCD_Details");
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DiseaseFK_Id")
                        .HasColumnType("int");

                    b.Property<bool>("EpilepsyVal")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.Allergies_Detail", b =>
                {
                    b.HasOne("ShortListOfHospitalManagement.Models.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortListOfHospitalManagement.Models.Patient", "Patient")
                        .WithMany("Allergies_Details")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.NCD_Detail", b =>
                {
                    b.HasOne("ShortListOfHospitalManagement.Models.NCD", "NCD")
                        .WithMany()
                        .HasForeignKey("NCDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShortListOfHospitalManagement.Models.Patient", "Patient")
                        .WithMany("NCD_Details")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NCD");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ShortListOfHospitalManagement.Models.Patient", b =>
                {
                    b.Navigation("Allergies_Details");

                    b.Navigation("NCD_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
